### ISSUE TITLE
Different picks for interests

### ISSUE THREAD

**Issue by Wallby** [datinglibre/DatingLibre#11]
How about changing the default interests to..
.. music
.. art
.. sports
.. engineering

I don't think that fitness is a great conversation starter.
Art includes reading and film (and more).
An engineering pick would be nice for those that engineer.

**Comment by datinglibre** [comment]
The demo site is for demonstration purposes only.

 I expect each installation will want different interests. These can be configured using the customization instructions:

https://github.com/datinglibre/DatingLibre/wiki/Customization#interests
